-
  name: Start Service in order
  hosts: localhost
  tasks:
   - name: Start the database server
     service: name-postgresql state=started
   - name: Start the httpd service
     service: name=httpd state=stated
   - name: Start the nginx Service
     service: 
       name: nginx
       state: started
