-
  name: Add DNS server to resolv.conf
  hosts: localhost
  tasks:
   - name: Ensure SELinux is set to enforcing mode
     ansible.builtin.lineinfile:
       path: /etc/selinux/config
       regexp: '^SELINUX='
       line: SELINUX=enforcing
   - lineinfile:
         path: /etc/resolv.conf
         line: 'nameserver 10.1.250.10'
   - name: Make sure group wheel is not in the sudoers configuration
     ansible.builtin.lineinfile:
       path: /etc/sudoers
       state: absent
       regexp: '^%wheel'
       
